version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1
#    environment:
#      - MYSQL_ROOT_PASSWORD
#      - MYSQL_DATABASE
#      - MYSQL_USER
#      - MYSQL_PASSWORD
    env_file:
      - .env
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:


